// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"my-clean-rchitecture/api/handler"
	"my-clean-rchitecture/app"
	"my-clean-rchitecture/domain/repo"
	"my-clean-rchitecture/domain/service"
)

// Injectors from wire.go:

func I() app.Server {
	db := app.NewDB()
	repos := repo.NewRepos(db)
	services := service.NewServices(repos)
	handlers := handler.NewHandlers(services)
	server := app.NewServer(handlers)
	return server
}
